const MovieArray = [
    {
        movieId: 1,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/uunchai-et00335262-1665386678.jpg",
        likes: 12,
        rating: 3.4,
        title: "UUNCHAI",
        language: "Hindi",
        format: "adventure/Drama/Family",
      
    },
    {
        movieId: 2,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/rocket-gang-et00136815-1668162428.jpg",
        likes: 21,
        rating: 4.0,
        title: "Rocket Gang",
        language: "Hindi/English",
        format: "Comedy/Fantasy/Horror/Musical",
    },
    {
        movieId: 3,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/black-panther-wakanda-forever-et00310792-1666006244.jpg",
        likes: 32,
        rating: 4.2,
        title: "Black Panther",
        language: "English/Tamil/Hindi/Telegu",
        format: "Action/Adventure/Drama",
    },
    {
        movieId: 4,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/drishyam-2-et00331997-1667547668.jpg",
        likes: 28,
        rating: 3.8,
        title: "Drishayam 2",
        language: "Hindi",
        format: "Drama/Mystery/Thriller",
    },
    {
        movieId: 5,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/kantara-hindi-et00342025-1665304124.jpg",
        likes: 43,
        rating: 3.0,
        title: "Kantra",
        language: "Hindi",
        format: "Adventure/Drama/Thriller",
    },
    {
        movieId: 6,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/ram-setu-et00300917-1665129549.jpg",
        likes: 24,
        rating: 1.2,
        title: "Ram Setu",
        language: "Hindi/Telugu/Tamil",
        format: "Adventure/Actiona/Thriller",
    },
    {
        movieId: 7,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/phone-bhoot-et00318521-1664878703.jpg",
        likes: 33,
        rating: 3.4,
        title: "Phone Bhoot",
        language: "Hindi",
        format: "Comedy/Horror",
    },
    {
        movieId: 8,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/yashoda-et00323318-1666012787.jpg",
        likes: 12,
        rating: 4.3,
        title: "Yashoda",
        language: "Telugu/Kannada/Hindi",
        format: "Sci-Fi/Thriller",
    },
    {
        movieId: 9,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/black-adam-et00117411-1665552700.jpg",
        likes: 34,
        rating: 4.7,
        title: "Black adam",
        language: "English/Hindi/Telugu/Tamil",
        format: "Action/Fantasy/Sci-Fi",
    },
    {
        movieId: 10,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/kulche-chole-et00338222-1666010094.jpg",
        likes: 233,
        rating: 2.8,
        title: "Kulche Chole",
        language: "Punjabi",
        format: "Comedy/Drama",
    },
    {
        movieId: 11,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/phone-bhoot-et00318521-1664878703.jpg",
        likes: 33,
        rating: 3.4,
        title: "Phone Bhoot",
        language: "Hindi",
        format: "Comedy/Horror",
    },
    {
        movieId: 12,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/uunchai-et00335262-1665386678.jpg",
        likes: 12,
        rating: 3.4,
        title: "UUNCHAI",
        language: "Hindi",
        format: "adventure/Drama/Family",
    },
    {
        movieId: 13,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/kantara-hindi-et00342025-1665304124.jpg",
        likes: 43,
        rating: 3.0,
        title: "Kantra",
        language: "Hindi",
        format: "Adventure/Drama/Thriller",
    },
    {
        movieId: 14,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/yashoda-et00323318-1666012787.jpg",
        likes: 12,
        rating: 4.3,
        title: "Yashoda",
        language: "Telugu/Kannada/Hindi",
        format: "Sci-Fi/Thriller",
    },
    {
        movieId: 15,
        poster: "https://assets-in.bmscdn.com/iedb/movies/images/mobile/thumbnail/xlarge/kantara-hindi-et00342025-1665304124.jpg",
        likes: 43,
        rating: 3.0,
        title: "Kantra",
        language: "Hindi",
        format: "Adventure/Drama/Thriller",
    },
]



export default MovieArray;